// <auto-generated />
using System;
using Comprexy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comprexy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ComprexyDbContext))]
    partial class ComprexyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Comprexy.Domain.Entities.CompressionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompressedTokens")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoldedMessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TokensAreEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkingMemoryVersionAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkingMemoryVersionBefore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("CompressionEvents", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("ConversationKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncedMessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationKey")
                        .IsUnique();

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FoldedIntoWorkingMemoryVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinnedForToolSchema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("RawWireJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "FoldedIntoWorkingMemoryVersion");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique();

                    b.ToTable("ConversationMessages", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.ConversationMetricsSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<double>("AverageTokenSavingsRatio")
                        .HasColumnType("REAL");

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("CompressionEventCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalActualTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBaselineTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCompressedPromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCompressionOverheadTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalNetTokensSaved")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalRawInputTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTurns")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("ConversationMetricsSummaries", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.ConversationToolCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("CatalogHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("CompactIndexJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SnapshottedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.ToTable("ConversationToolCatalogs", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.ConversationToolDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("HydratedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId");

                    b.HasIndex("ConversationId", "ToolName")
                        .IsUnique();

                    b.ToTable("ConversationToolDefinitions", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.ConversationTurnMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("ActualCompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualPromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaselineTotalTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("CompressedInputTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompressedTotalTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HardBudgetExceeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("NetTokenSavingsRatio")
                        .HasColumnType("REAL");

                    b.Property<int>("NetTokensSaved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RawInputTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RawMessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestStartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SentMessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SentPayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftBudgetExceeded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrimTriggered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkingMemoryVersionUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.HasIndex("ConversationId", "TurnIndex")
                        .IsUnique();

                    b.ToTable("ConversationTurnMetrics", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.WorkingMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "Version")
                        .IsUnique();

                    b.ToTable("WorkingMemories", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
