// <auto-generated />
using System;
using Comprexy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comprexy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ComprexyDbContext))]
    partial class ComprexyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Comprexy.Domain.Entities.CompressionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompressedTokens")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoldedMessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TokensAreEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkingMemoryVersionAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkingMemoryVersionBefore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("CompressionEvents", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("ConversationKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EffectiveSettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncedMessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationKey")
                        .IsUnique();

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FoldedIntoWorkingMemoryVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawWireJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "FoldedIntoWorkingMemoryVersion");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique();

                    b.ToTable("ConversationMessages", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.ConversationMetricsSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<double>("AverageTokenSavingsRatio")
                        .HasColumnType("REAL");

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("CompressionEventCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalActualTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBaselineTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCompressedPromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCompressionOverheadTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalNetTokensSaved")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalRawInputTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTurns")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalVirtualToolsTokensSaved")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("ConversationMetricsSummaries", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.ConversationToolCallMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("ClientArgumentsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientCallId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientToolName")
                        .HasColumnType("TEXT");

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComprexyToolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IrArgumentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IrCallId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<long>("RegisteredAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "ClientCallId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "IrCallId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "Pending", "RegisteredAt");

                    b.ToTable("ConversationToolCallMaps", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.ConversationToolCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("CatalogHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MappingJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SnapshottedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ToolIrDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.ToTable("ConversationToolCatalogs", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.ConversationToolDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId");

                    b.HasIndex("ConversationId", "ToolName")
                        .IsUnique();

                    b.ToTable("ConversationToolDefinitions", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.ConversationTurnMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("ActualCompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualPromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaselineTotalTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("CompressedInputTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompressedTotalTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HardBudgetExceeded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IrFullInputTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("NetTokenSavingsRatio")
                        .HasColumnType("REAL");

                    b.Property<int>("NetTokensSaved")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrepareDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RawInputTokensEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RawMessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestStartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SentMessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SentPayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftBudgetExceeded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrimTriggered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpstreamDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VirtualToolsTokensSaved")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkingMemoryVersionUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.HasIndex("ConversationId", "TurnIndex")
                        .IsUnique();

                    b.ToTable("ConversationTurnMetrics", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.ModelPricingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<decimal?>("CachedInputUsdPer1M")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CachedOutputUsdPer1M")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("USD");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InputUsdPer1M")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OutputUsdPer1M")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ModelKey")
                        .IsUnique();

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("ModelPricingEntries", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.OperatorSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("OperatorSettings", (string)null);
                });

            modelBuilder.Entity("Comprexy.Domain.Entities.WorkingMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<long>("ClusterId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "Version")
                        .IsUnique();

                    b.ToTable("WorkingMemories", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
